@startuml

package services {
    package xml {
        class Parser {
            CityMap getStreetSections(pathToXml: String)
            DeliveryRequest getDeliveryRequest(pathToXml: String)
        }
    }

    package tsp {
        abstract class TspSolver {
            +{abstract} Planning solve(graph: DeliveryGraph)
        }

        class BasicTspSolver {
            +Planning solve(graph: DeliveryGraph)
        }

        class AdvancedTspSolver {
            +Planning solve(graph: DeliveryGraph)
        }

        TspSolver <|-- BasicTspSolver
        TspSolver <|-- AdvancedTspSolver

    }
}



@enduml
