@startuml

package services {
    package xml {
        class Parser {
        }
    }

    package tsp {
        abstract class TspSolver {
        }

        class BasicTspSolver {
        }

        class AdvancedTspSolver {
        }

        class WayPointIterator {
        }
    }
}

package models {
    class CityMap {
    }

    class Planning {
    }

    class DeliveryRequest {
    }
}

package components {
    package application {
        class MainController {
        }
    }
}

package view {
    class MainView
}

MainController -left-> Parser
MainController -right-> CityMap
MainController -right-> Planning
MainController -right-> DeliveryRequest
MainController -up-> MainView

MainController --> tsp

@enduml
