class Exception
package services.xml.exception {

    abstract class ParserException
    abstract class ParserSemanticException
    abstract class ParserSyntaxException
    
    abstract class ParserSemanticException
    class ParserDuplicateObjectException
    class ParserIntegerValueException
    class ParserShouldBeIntegerValueException
    
    abstract class ParserSyntaxException
    abstract class ParserNodesNumberException
    class ParserInvalidIdException
    class ParserMalformedXmlException
    
    abstract class ParserNodesNumberException
    class ParserBoundedNodesNumberException
    class ParserLowerBoundedNodesNumberException
    
    Exception <|-- ParserException
    
    ParserException <|-- ParserSyntaxException
    ParserException <|-- ParserSemanticException
    
    ParserSemanticException <|-- ParserDuplicateObjectException
    ParserSemanticException <|-- ParserIntegerValueException
    ParserSemanticException <|-- ParserShouldBeIntegerValueException
    ParserSemanticException <|-- ParserInvalidIdException
    
    ParserSyntaxException <|-- ParserNodesNumberException
    ParserSyntaxException <|-- ParserMalformedXmlException
    
    ParserNodesNumberException <|-- ParserBoundedNodesNumberException
    ParserNodesNumberException <|-- ParserLowerBoundedNodesNumberException
}
