@startuml
participant "Controller" as Ctrl
participant "GraphFactory" as GF
participant "TSPSolver" as TSPS
participant "cityMap: CityMap" as CM


[-> Ctrl: computePlanning()
activate Ctrl

'Instanciate with a strategy
create GF
Ctrl -> GF: <<create(GraphFactoryStrategy)>>
'Instanciate with a strategy
create TSPS
Ctrl -> TSPS: <<create(BranchStrategy, BoundStrategy)>>


Ctrl -> GF: computeDeliveryGraph(cityMap, DeliveryRequest)
activate GF

GF -> CM: getIntersections()
activate CM
GF <<-- CM: intersactions: Map<int, Intersection>
deactivate CM

GF -> CM: getStreetSections()
activate CM
GF <<-- CM: streetSections: Map<int,  Map<int, StreetSection>>
deactivate CM

Ctrl <<-- GF: deliveryGraph: DeliveryGraph
deactivate GF


Ctrl -> TSPS: computePlanning(deliveryGraph, DeliveryRequest)
activate TSPS
Ctrl <<-- TSPS: Planning
deactivate TSPS



Ctrl -> Ctrl: setCurrentPlanning(Planning)
activate Ctrl
deactivate Ctrl

deactivate Ctrl

@enduml
