@startuml

[*] --> WaitOpenCityMap

WaitOpenCityMap --> OpenedCityMap: openCityMap
OpenedCityMap --> OpenedCityMap: openCityMap

state OpenedCityMap {
    [*] --> WaitOpenDeliveryRequest

    WaitOpenDeliveryRequest --> OpenedDeliveryRequest: openDeliveryRequest
    OpenedDeliveryRequest --> OpenedDeliveryRequest: openDeliveryRequest

    state OpenedDeliveryRequest {
        [*] --> Ready

        Ready --> ComputingPlanning: computePlanning
        ComputingPlanning --> Ready: success, cancel, error

        Ready --> AddDeliveryAddress: addDeliveryAddress
        AddDeliveryAddress --> Ready: cancel, MapView#click
    }

    --

    [*] --> DisplayMap

    DisplayMap --> DragMap: MapView#mousePressed
    DragMap --> DragMap: mouseDragged | translateMap()
    DragMap --> DisplayMap: mouseReleased
}

@enduml
